# Telemetry-free fork of ahujasid/ableton-mcp.
# Originally generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Build dependencies for wheels that lack musl builds
RUN apk add --no-cache gcc musl-dev libffi-dev

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir .

# The MCP server speaks stdio to its client and TCP to the Ableton Remote
# Script (ABLETON_HOST:ABLETON_PORT, default localhost:9877). It opens no
# other connections — there is no telemetry or dataset upload in this fork.
ENV ABLETON_HOST=localhost \
    ABLETON_PORT=9877

# The console script is the package's entry point (ableton_mcp.app:main).
CMD ["ableton-mcp"]
