"""
Guardrail: no telemetry, ever — CLAUDE.md hard rule 1, mechanized.

This fork exists because upstream collects prompts, MIDI, and track/clip
names. Three checks (docs/REFACTOR_PLAN.md §5 guardrail table):

1. the CLAUDE.md verification grep as a test — the telemetry vocabulary must
   never reappear in either half,
2. no HTTP client is ever imported — the server's only outbound connection is
   TCP to the local Ableton socket,
3. `socket` itself is imported only where the transport lives (an explicit
   allowlist; it shrinks to `connection.py` when the transport moves in the
   refactor's PR8).

Runs anywhere — no Ableton, no network.
"""

import ast
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SCANNED_DIRS = (
    REPO_ROOT / "src" / "ableton_mcp",
    REPO_ROOT / "AbletonMCP_Remote_Script",
)

# CLAUDE.md: grep -ri "telemetry|supabase|analytics|dataset|trajectory"
TELEMETRY_VOCABULARY = re.compile(
    r"telemetry|supabase|analytics|dataset|trajectory", re.IGNORECASE
)

# Module roots that mean an outbound HTTP client. urllib.request / http.client
# are called out as submodules because `urllib` and `http` also contain
# harmless pieces (urllib.parse, http.HTTPStatus).
FORBIDDEN_IMPORT_ROOTS = {"requests", "urllib3", "httpx", "aiohttp"}
FORBIDDEN_SUBMODULES = {"urllib.request", "http.client"}

# The only files allowed to import `socket`. This list is expected to SHRINK:
# after the transport extraction (docs/REFACTOR_PLAN.md §3.5, PR8) the server
# entry becomes src/ableton_mcp/connection.py and server.py leaves the list.
# The bundled file is the generated byte-identical copy of the Remote Script
# (enforced by test_bundle_identity), so it carries the same import.
SOCKET_IMPORT_ALLOWLIST = {
    "src/ableton_mcp/server.py",
    "AbletonMCP_Remote_Script/__init__.py",
    "src/ableton_mcp/bundled_ableton_remote_script/AbletonMCP_init.py",
}


def _python_sources():
    files = []
    for base in SCANNED_DIRS:
        assert base.is_dir(), f"missing source dir: {base}"
        files.extend(
            p for p in sorted(base.rglob("*.py")) if "__pycache__" not in p.parts
        )
    assert files, "no Python sources found to scan"
    return files


def _relative(path):
    return path.relative_to(REPO_ROOT).as_posix()


def _imported_modules(path):
    """Every module name an `import`/`from ... import` statement touches."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    modules = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            modules.add(node.module)
            # `from urllib import request` reaches urllib.request just as well
            modules.update(f"{node.module}.{alias.name}" for alias in node.names)
    return modules


def test_telemetry_vocabulary_never_reappears():
    hits = []
    for path in _python_sources():
        for lineno, line in enumerate(
            path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1
        ):
            if TELEMETRY_VOCABULARY.search(line):
                hits.append(f"{_relative(path)}:{lineno}: {line.strip()}")
    assert hits == [], "telemetry vocabulary found (CLAUDE.md hard rule 1):\n" + "\n".join(hits)


def test_no_http_client_is_ever_imported():
    offenders = []
    for path in _python_sources():
        for module in _imported_modules(path):
            root = module.split(".")[0]
            if root in FORBIDDEN_IMPORT_ROOTS or any(
                module == sub or module.startswith(sub + ".")
                for sub in FORBIDDEN_SUBMODULES
            ):
                offenders.append(f"{_relative(path)}: import {module}")
    assert offenders == [], (
        "outbound-capable HTTP client imported — the only outbound connection "
        "allowed is TCP to the local Ableton socket:\n" + "\n".join(offenders)
    )


def test_socket_imported_only_in_the_transport_allowlist():
    offenders = []
    for path in _python_sources():
        modules = _imported_modules(path)
        imports_socket = any(m == "socket" or m.startswith("socket.") for m in modules)
        if imports_socket and _relative(path) not in SOCKET_IMPORT_ALLOWLIST:
            offenders.append(_relative(path))
    assert offenders == [], (
        f"socket imported outside the transport allowlist: {offenders}"
    )
    # And the allowlisted transport files really are the ones importing it —
    # a stale allowlist would quietly stop guarding anything.
    importing = {
        _relative(p) for p in _python_sources() if "socket" in _imported_modules(p)
    }
    assert importing == SOCKET_IMPORT_ALLOWLIST
